// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test3() {
    driver.get("https://www.naver.com/");
    driver.manage().window().setSize(new Dimension(1008, 875));
    js.executeScript("window.scrollTo(0,267)");
    js.executeScript("window.scrollTo(0,551)");
    {
      WebElement element = driver.findElement(By.cssSelector(".ContentPagingView-module__btn_next___ZBhby"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".TooltipView-module__paging___O0x6W")).click();
    driver.findElement(By.cssSelector(".ContentPagingView-module__btn_next___ZBhby")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ContentPagingView-module__btn_next___ZBhby"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".id_living .ContentHeaderView-module__tab_item___dz3nK:nth-child(3) > .ContentHeaderView-module__tab___uYoNi")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("요일별 웹툰")).click();
    vars.put("win7971", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7971").toString());
  }
}
